### ISSUE TITLE
[keycloak - OID4VCI] Simplify SD-JWT API usage

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-oid4vc#10]
This is a proxy of:

- [x] https://github.com/keycloak/keycloak/issues/32955

**Comment by Awambeng** [comment]
I submitted a pr this morning https://github.com/keycloak/keycloak/pull/34915

**Comment by nitch2019** [comment]
wait for the ticket to be merged

**Comment by Awambeng** [comment]
It has been merged already
