### ISSUE TITLE
Keycloak native verification of an SD-JWT based vp_token

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-oid4vc#2]
This is a proxy of:
- [x] https://github.com/keycloak/keycloak/issues/29859

**Comment by nitch2019** [comment]
@IngridPuppet pls turn the ticket in Epic and let create tasks for it

**Comment by IngridPuppet** [comment]
Keycloak already has code for creating and verifying SD-JWTs tokens. We would like to extend the verification framework to make it more readily reusable.

First, what this task is not about: we're not trying to verify VP tokens within a specific life cycle, nor are we attempting to implement OpenID for VP. This task solely aims to define a verification framework that can be easily integrated in unknown Keycloak flows. That said, everything will be added to the core package.

Now we have to think, beyond asserting the integrity of a VP token (SD-JWT presentation), what do we need to accept it ?

1. A VP token is presented for a purpose, proving some claims. We therefore need a set of claim requirements to verify the conformance of a token against. The perfect format for this purpose is a Presentation Definition.

2. Another critical aspect in accepting VP tokens is whether or not we trust and even expect their issuers. According to whether Issuers expose public keys via JWT VC Issuer Metadata, resolvable DID documents, or embedding X509 certificates in issued tokens, ensuring trust may range from double checking issuer URIs, DID addresses, or validating their certificates. We need a way to abstract all this and retrieve public keys safely.

**Comment by nitch2019** [comment]
Need more clarification.
We will plan a workshop to go deeper in the topic

**Comment by IngridPuppet** [comment]
Unfortunately, proper presentation definitions would require JSON path and JSON schema libraries, and none of them are already added to Keycloak. I'll proceed with a simpler framework constraining fields with regex values.

**Comment by IngridPuppet** [comment]
I'm almost done; tests are missing. However, I'll have to pause the task to work on new urgent tickets.

**Comment by IngridPuppet** [comment]
Resumed working on this.

**Comment by IngridPuppet** [comment]
Pending PR at Keycloak:
- https://github.com/keycloak/keycloak/pull/33752
