### ISSUE TITLE
[keycloak - OID4VCI] Migrate Verifiable Credential Definitions from Client Attributes to Realm Level Attributes

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-oid4vc#6]
This is a proxy of:
- [x] https://github.com/keycloak/keycloak/issues/32773

**Comment by Ogenbertrand** [comment]
Closes https://github.com/keycloak/keycloak/pull/34697/

**Comment by Ogenbertrand** [comment]
MR-https://github.com/keycloak/keycloak/pull/34796

**Comment by nitch2019** [comment]
waitibg for the merge on KC
