### ISSUE TITLE
[keycloak - OID4VCI] Create a CredentialBuilderProvider interface

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-oid4vc#8]
This is a proxy of:

- [x] https://github.com/keycloak/keycloak/issues/32951

**Comment by IngridPuppet** [comment]
This may be fixed by:
- https://github.com/keycloak/keycloak/pull/35046

**Comment by hugoib** [comment]
Waiting for KC review.

**Comment by nitch2019** [comment]
in Review by @IngridPuppet for new comment
