### ISSUE TITLE
Implement simple first verification of a claim

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-oid4vc#9]
### Description
Verification will be the most critical element in the SSI ecosystem. The evolving complexity of verifiers is already materializing two architecture models:

1. The embedded adapter, that verifies the presentation before filling up the context of the relying party with authorization information
2. The external adapter that exposes a verification API to the relying party.

The purpose of this ticket is to:

1. Design the embedded adapter and then
2. Expose it thru an API

See the Sample Implementation : Walt.ID bellow as orientation.

Spec: https://drafts.oauth.net/oauth-sd-jwt-vc/draft-ietf-oauth-sd-jwt-vc.html#section-3.4
Spec: https://drafts.oauth.net/oauth-sd-jwt-vc/draft-ietf-oauth-sd-jwt-vc.html#section-3.5
https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#section-5.3.2

### Artifact
This is supposed to be a pure java component that performs the SD_JWT validation. We shall have the possibility to use this component in:

1. Inside keycloak. In case keycloak act as a federated identity provided
2. Inside an adapter component of a quarkus service or a springboot service.
3. In a java based endroid holder component.

### Sample Implementation : Walt.ID

1. This video show a sample usage of the walt.id verification API: https://docs.oss.walt.id/verifier/api/getting-started
2. I do like the fact that they have a verification policy designed: https://docs.oss.walt.id/verifier/api/policies
3. This is a short explanation of a verification API provided by walt.id: https://docs.oss.walt.id/verifier/api/vc-oid4vc
4. Sources: https://docs.oss.walt.id/verifier/api/setup/open-source
5. More sources. SDKs: https://docs.oss.walt.id/verifier/sdks/getting-started

### Before You Start
Have a look at [how to contribute](https://github.com/adorsys/keycloak-oid4vc/discussions/19)

**Comment by francis-pouatcha** [comment]
Verification must be performed by in the consuming module. In keycloak Services.

**Comment by francis-pouatcha** [comment]
Here is a sample implementation from EU: https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/blob/main/src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt

**Comment by francis-pouatcha** [comment]
Sample modular implementation of verification using verifier policies: https://docs.walt.id/v/web-wallet/configuration-and-setup/verifier-portal-setup

**Comment by bengo237** [comment]
https://github.com/adorsys/sd-jwt/pull/1

**Comment by hugoib** [comment]
There was a first MR: https://github.com/adorsys/sd-jwt/pull/1 

There are still validations to be implemented.

**Comment by nitch2019** [comment]
@francis-pouatcha please break the tickets down into smaller tasks

**Comment by Marcjazz** [comment]
Here a breakdown of the ticket

- https://github.com/adorsys/eudiw-app/issues/102
- https://github.com/adorsys/eudiw-app/issues/99

**Comment by nitch2019** [comment]
@Marcjazz please check the subtasks and close this ticket

**Comment by Marcjazz** [comment]
Still one to go before closing this ticket: 
- https://github.com/adorsys/eudiw-verifier/issues/4
